# 戳一戳回复消息
poke_responses:
  - "别戳啦！"
  - "哎呀，还戳呀，别闹啦！"
  - "别戳我啦  你要做什么  不理你了"

# 表情包 API type 映射
emoji_url_mapping:
  阿罗娜扔: "13"
  咖波画: "33"
  咖波指: "34"
  咖波蹭: "36"
  丢: "38"
  撕: "56"
  爬: "69"
  顶: "102"
  拍: "184"
  摸: "187"
  捏: "188"
  普拉娜吃: "191"
  捣: "199"

# 随机触发表情包的概率
random_emoji_trigger_probability: 0.5
# 请求超时时间
post_timeout: 20
# 功能开关
feature_switches:
  poke_response_enabled: true  # 戳机器人回复功能开关
  poke_back_enabled: true  # 戳回功能开关
  emoji_trigger_enabled: true  # 触发表情包功能开关

# 戳 Bot 反击相关概率
poke_back_probability: 0.3  # 戳 Bot 后反击的概率
super_poke_probability: 0.1  # 超级加倍（多次戳回）的概率
